const EErrors = {
  USER_NOT_FOUND: 1,
  USER_ALREADY_EXISTS: 2,
  USER_NOT_AUTHORIZED: 3,
  EMPTY_DB: 4,
  FAILED_HASH: 5,
  TOKEN_ERROR: 6,
  TOKEN_NOT_FOUND: 7,
  EXPIRED_TOKEN: 8,
  INTERNAL_SERVER_ERROR: 9,
  AUTHORIZATION_ERROR: 10,
  ORDER_CREATION_ERROR: 11,
  NOT_FOUND: 12,
  BAD_REQUEST: 13,
};

export default EErrors;
